#!/usr/bin/env python3
"""Standby-first client upgrade window validator.

Consumes the Task 1 generated lock snapshot, a client-upgrade change record,
the Task 2 active-standby state authority, and (in aws mode) the AWS Standby
canary soak evidence. Emits exactly one line:

    CLIENT_UPGRADE_WINDOW=PASS site=<site> record_sha256=<sha256>   (stdout)
    CLIENT_UPGRADE_WINDOW=FAIL reason=<stable_reason_code>          (stderr)

The root copy under shared/scripts is the only edit authority; the package
copy is a generated byte-identical mirror. This file is intentionally
self-contained so the installed host copy has no repository imports.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import stat
import sys
from datetime import datetime, timezone
from pathlib import Path


sys.dont_write_bytecode = True

RFC3339_UTC = re.compile(r"^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z$")
SEMVER = re.compile(r"^[0-9]+\.[0-9]+\.[0-9]+$")
SHA256_HEX = re.compile(r"^[0-9a-f]{64}$")
RECORD_ID = re.compile(r"^CR-[A-Za-z0-9][A-Za-z0-9._-]{2,63}$")
OPERATOR_ID = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._@-]{0,63}$")

RECORD_REQUIRED = (
    "schema_version",
    "record_id",
    "network",
    "lock_sha256",
    "clients",
    "approvals",
    "windows",
    "standby_soak",
    "standby_evidence_sha256",
)
EVIDENCE_REQUIRED = (
    "schema_version",
    "record_id",
    "lock_sha256",
    "site",
    "healthy",
    "vc_sealed",
    "vc_key_absent",
    "soak_started_at",
    "soak_completed_at",
    "samples",
)
SOAK_SAMPLE_COUNT = 13
SOAK_SAMPLE_SPACING_SECONDS = 300
NO_GO_COMMON_CLIENT = "NO_GO_COMMON_CLIENT"


class UpgradeWindowError(Exception):
    def __init__(self, reason: str):
        super().__init__(reason)
        self.reason = reason


def parse_utc(value: object, reason: str) -> datetime:
    if not isinstance(value, str) or not RFC3339_UTC.match(value):
        raise UpgradeWindowError(reason)
    return datetime.strptime(value, "%Y-%m-%dT%H:%M:%SZ").replace(tzinfo=timezone.utc)


def require_secure_file(path: Path, expected_mode: int, prefix: str) -> None:
    try:
        metadata = path.lstat()
    except FileNotFoundError:
        raise UpgradeWindowError(f"{prefix}_READ_FAILED")
    except OSError:
        raise UpgradeWindowError(f"{prefix}_READ_FAILED")
    if stat.S_ISLNK(metadata.st_mode) or not stat.S_ISREG(metadata.st_mode):
        raise UpgradeWindowError(f"{prefix}_NOT_REGULAR")
    if stat.S_IMODE(metadata.st_mode) != expected_mode:
        raise UpgradeWindowError(f"{prefix}_MODE_INVALID")


def read_json_bytes(path: Path, prefix: str) -> tuple[bytes, object]:
    try:
        raw = path.read_bytes()
    except OSError:
        raise UpgradeWindowError(f"{prefix}_READ_FAILED")
    try:
        return raw, json.loads(raw.decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError):
        raise UpgradeWindowError(f"{prefix}_INVALID")


def load_lock_snapshot(path: Path) -> dict:
    try:
        raw = path.read_bytes()
    except OSError:
        raise UpgradeWindowError("LOCK_READ_FAILED")
    try:
        snapshot = json.loads(raw.decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError):
        raise UpgradeWindowError("LOCK_INVALID")
    if not isinstance(snapshot, dict):
        raise UpgradeWindowError("LOCK_INVALID")
    source_sha = snapshot.get("source_lock_sha256")
    lock = snapshot.get("client_release_lock")
    if not isinstance(source_sha, str) or not SHA256_HEX.match(source_sha) or not isinstance(lock, dict):
        raise UpgradeWindowError("LOCK_INVALID")
    for client in ("nethermind", "lighthouse"):
        entry = lock.get(client)
        if not isinstance(entry, dict) or not isinstance(entry.get("version"), str) \
                or not SEMVER.match(entry["version"]):
            raise UpgradeWindowError("LOCK_INVALID")
    skew = lock.get("approved_skew")
    if not isinstance(skew, dict) or not isinstance(skew.get("enabled"), bool):
        raise UpgradeWindowError("LOCK_INVALID")
    if lock.get("network") != "hoodi":
        raise UpgradeWindowError("LOCK_INVALID")
    return {"source_lock_sha256": source_sha, "lock": lock}


def validate_window(window: object) -> tuple[datetime, datetime]:
    if not isinstance(window, dict) or set(window) != {"starts_at", "ends_at"}:
        raise UpgradeWindowError("RECORD_INVALID")
    starts = parse_utc(window["starts_at"], "RECORD_INVALID")
    ends = parse_utc(window["ends_at"], "RECORD_INVALID")
    if starts >= ends:
        raise UpgradeWindowError("WINDOW_INVALID")
    return starts, ends


def validate_record(document: object) -> dict:
    if not isinstance(document, dict) or set(document) != set(RECORD_REQUIRED):
        raise UpgradeWindowError("RECORD_INVALID")
    if document["schema_version"] != "client-upgrade-change-record-v1":
        raise UpgradeWindowError("RECORD_INVALID")
    if not isinstance(document["record_id"], str) or not RECORD_ID.match(document["record_id"]):
        raise UpgradeWindowError("RECORD_INVALID")
    if document["network"] != "hoodi":
        raise UpgradeWindowError("RECORD_INVALID")
    if not isinstance(document["lock_sha256"], str) or not SHA256_HEX.match(document["lock_sha256"]):
        raise UpgradeWindowError("RECORD_INVALID")
    if not isinstance(document["standby_evidence_sha256"], str) \
            or not SHA256_HEX.match(document["standby_evidence_sha256"]):
        raise UpgradeWindowError("RECORD_INVALID")

    clients = document["clients"]
    if not isinstance(clients, dict) or set(clients) != {"nethermind", "lighthouse"}:
        raise UpgradeWindowError("RECORD_INVALID")
    for client in ("nethermind", "lighthouse"):
        change = clients[client]
        if not isinstance(change, dict) or set(change) != {"before_version", "after_version"}:
            raise UpgradeWindowError("RECORD_INVALID")
        for key in ("before_version", "after_version"):
            if not isinstance(change[key], str) or not SEMVER.match(change[key]):
                raise UpgradeWindowError("RECORD_INVALID")

    approvals = document["approvals"]
    if not isinstance(approvals, list) or len(approvals) != 2:
        raise UpgradeWindowError("RECORD_INVALID")
    operators = []
    for approval in approvals:
        if not isinstance(approval, dict) or set(approval) != {"operator", "approved_at"}:
            raise UpgradeWindowError("RECORD_INVALID")
        operator = approval["operator"]
        if not isinstance(operator, str) or not OPERATOR_ID.match(operator):
            raise UpgradeWindowError("RECORD_INVALID")
        parse_utc(approval["approved_at"], "RECORD_INVALID")
        operators.append(operator)
    if operators[0] == operators[1]:
        raise UpgradeWindowError("RECORD_INVALID")

    windows = document["windows"]
    if not isinstance(windows, dict) or set(windows) != {"standby", "aws"}:
        raise UpgradeWindowError("RECORD_INVALID")
    standby_window = validate_window(windows["standby"])
    aws_window = validate_window(windows["aws"])
    soak_window = validate_window(document["standby_soak"])

    if aws_window[0] < standby_window[1] and standby_window[0] < aws_window[1]:
        raise UpgradeWindowError("WINDOW_OVERLAP")
    if aws_window[0] < standby_window[1]:
        raise UpgradeWindowError("STANDBY_FIRST_VIOLATION")
    if soak_window[0] < standby_window[0] or soak_window[1] > standby_window[1]:
        raise UpgradeWindowError("SOAK_INVALID")
    if int((soak_window[1] - soak_window[0]).total_seconds()) \
            != SOAK_SAMPLE_SPACING_SECONDS * (SOAK_SAMPLE_COUNT - 1):
        raise UpgradeWindowError("SOAK_INVALID")

    return {
        "document": document,
        "standby_window": standby_window,
        "aws_window": aws_window,
        "soak_window": soak_window,
    }


def validate_state(document: object) -> None:
    if not isinstance(document, dict):
        raise UpgradeWindowError("STATE_INVALID")
    if document.get("schema_version") != "active-standby-state-v1":
        raise UpgradeWindowError("STATE_INVALID")
    for key in ("to_state", "mode"):
        if not isinstance(document.get(key), str):
            raise UpgradeWindowError("STATE_INVALID")
    no_go = document.get("no_go_reason")
    if no_go == NO_GO_COMMON_CLIENT:
        raise UpgradeWindowError(NO_GO_COMMON_CLIENT)
    if no_go is not None:
        raise UpgradeWindowError("STATE_NO_GO_ACTIVE")
    if document["to_state"] != "S0" or document["mode"] != "NORMAL":
        raise UpgradeWindowError("STATE_NOT_S0")


def validate_skew(lock: dict, record: dict, now: datetime) -> None:
    changes = record["clients"]
    for client in ("nethermind", "lighthouse"):
        if changes[client]["after_version"] != lock["lock"][client]["version"]:
            raise UpgradeWindowError("TARGET_VERSION_MISMATCH")
    needs_skew = any(
        changes[client]["before_version"] != changes[client]["after_version"]
        for client in ("nethermind", "lighthouse")
    )
    if not needs_skew:
        return
    skew = lock["lock"]["approved_skew"]
    if skew.get("enabled") is not True \
            or skew.get("change_record") != record["record_id"] \
            or skew.get("site") != "standby":
        raise UpgradeWindowError("SKEW_NOT_APPROVED")
    expires_at = parse_utc(skew.get("expires_at"), "SKEW_NOT_APPROVED")
    if expires_at <= now:
        raise UpgradeWindowError("SKEW_EXPIRED")


def validate_evidence(raw: bytes, document: object, record: dict, soak_window: tuple[datetime, datetime],
                      now: datetime) -> None:
    if hashlib.sha256(raw).hexdigest() != record["standby_evidence_sha256"]:
        raise UpgradeWindowError("EVIDENCE_HASH_MISMATCH")
    if not isinstance(document, dict) or set(document) != set(EVIDENCE_REQUIRED):
        raise UpgradeWindowError("EVIDENCE_INVALID")
    if document["schema_version"] != "client-upgrade-standby-evidence-v1" or document["site"] != "standby":
        raise UpgradeWindowError("EVIDENCE_INVALID")
    if document["record_id"] != record["record_id"] or document["lock_sha256"] != record["lock_sha256"]:
        raise UpgradeWindowError("EVIDENCE_RECORD_MISMATCH")
    for key in ("healthy", "vc_sealed", "vc_key_absent"):
        if not isinstance(document[key], bool):
            raise UpgradeWindowError("EVIDENCE_INVALID")
    if document["vc_sealed"] is not True or document["vc_key_absent"] is not True:
        raise UpgradeWindowError("EVIDENCE_VC_NOT_SEALED")
    if document["healthy"] is not True:
        raise UpgradeWindowError("EVIDENCE_UNHEALTHY")

    started = parse_utc(document["soak_started_at"], "EVIDENCE_INVALID")
    completed = parse_utc(document["soak_completed_at"], "EVIDENCE_INVALID")
    if (started, completed) != soak_window:
        raise UpgradeWindowError("SOAK_MISMATCH")

    samples = document["samples"]
    if not isinstance(samples, list) or len(samples) != SOAK_SAMPLE_COUNT:
        raise UpgradeWindowError("SOAK_INVALID")
    parsed_samples = [parse_utc(sample, "SOAK_INVALID") for sample in samples]
    if parsed_samples[0] != started or parsed_samples[-1] != completed:
        raise UpgradeWindowError("SOAK_INVALID")
    for earlier, later in zip(parsed_samples, parsed_samples[1:]):
        if int((later - earlier).total_seconds()) != SOAK_SAMPLE_SPACING_SECONDS:
            raise UpgradeWindowError("SOAK_INVALID")
    if completed > now:
        raise UpgradeWindowError("SOAK_NOT_COMPLETE")


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(add_help=True)
    parser.add_argument("--lock", required=True)
    parser.add_argument("--record", required=True)
    parser.add_argument("--state", required=True)
    parser.add_argument("--standby-evidence", required=True)
    parser.add_argument("--site", required=True, choices=("aws", "standby"))
    parser.add_argument("--now", required=True)
    return parser.parse_args()


def main() -> int:
    arguments = parse_arguments()
    now = parse_utc(arguments.now, "NOW_INVALID")

    lock = load_lock_snapshot(Path(arguments.lock))

    record_path = Path(arguments.record)
    require_secure_file(record_path, 0o640, "RECORD")
    record_raw, record_document = read_json_bytes(record_path, "RECORD")
    record = validate_record(record_document)

    state_path = Path(arguments.state)
    require_secure_file(state_path, 0o600, "STATE")
    _, state_document = read_json_bytes(state_path, "STATE")
    validate_state(state_document)

    if record["document"]["lock_sha256"] != lock["source_lock_sha256"]:
        raise UpgradeWindowError("LOCK_HASH_MISMATCH")
    validate_skew(lock, record["document"], now)

    site_window = record["standby_window"] if arguments.site == "standby" else record["aws_window"]
    if not site_window[0] <= now <= site_window[1]:
        raise UpgradeWindowError("NOT_IN_WINDOW")

    evidence_path = Path(arguments.standby_evidence)
    if arguments.site == "standby":
        aws_window = record["aws_window"]
        if aws_window[0] <= now <= aws_window[1]:
            raise UpgradeWindowError("AWS_WINDOW_OPEN")
        if evidence_path.parent.is_dir() and (evidence_path.is_symlink() or evidence_path.exists()):
            require_secure_file(evidence_path, 0o640, "EVIDENCE")
    else:
        require_secure_file(evidence_path, 0o640, "EVIDENCE")
        evidence_raw, evidence_document = read_json_bytes(evidence_path, "EVIDENCE")
        validate_evidence(evidence_raw, evidence_document, record["document"], record["soak_window"], now)

    record_sha256 = hashlib.sha256(record_raw).hexdigest()
    print(f"CLIENT_UPGRADE_WINDOW=PASS site={arguments.site} record_sha256={record_sha256}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except UpgradeWindowError as error:
        print(f"CLIENT_UPGRADE_WINDOW=FAIL reason={error.reason}", file=sys.stderr)
        raise SystemExit(1)
    except OSError:
        print("CLIENT_UPGRADE_WINDOW=FAIL reason=INPUT_IO_FAILED", file=sys.stderr)
        raise SystemExit(1)
